server:
  port: 20040
  servlet:
    context-path: /chat

spring:
  application:
    name: easychat-chat-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ec0b2714-22be-45cc-800e-fa801b4e94db
        cluster-name: shanghai
        group: easychat
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/easychat?characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    host: localhost
    port: 6379
    password: 123456
    connect-timeout: 5000

mybatis-plus:
  configuration:
    local-cache-scope: statement # 一级缓存
    cache-enabled: false # 二级缓存
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
  mapper-locations: classpath:/mapper/*.xml

# SocketIO配置
socketio:
  # SocketIO端口
  port: 9092
  # 连接数大小
  workCount: 100
  # 允许客户请求
  allowCustomRequests: true
  # 协议升级超时时间(毫秒)，默认10秒，HTTP握手升级为ws协议超时时间
  upgradeTimeout: 10000
  # Ping消息超时时间(毫秒)，默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 60000
  # Ping消息间隔(毫秒)，默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
  # 设置HTTP交互最大内容长度
  maxHttpContentLength: 1048576
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
